os: linux
dist: xenial
group: beta
language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

jobs:
  fast_finish: true
  allow_failures:
    - env: CAN_FAIL=true
  include:
    - stage: tests
      name: "Linter"
      script: npm run lint
      env: CAN_FAIL=true

    - stage: tests
      name: "Unit tests (using Truffle)"
      script: npm run truffle:test

    - stage: tests
      name: "Unit tests (using Hardhat)"
      script: npm run hardhat:test

    - stage: tests
      name: "Unit tests with coverage report"
      script: npm run coverage

    - stage: tests
      name: "Unit tests using solc nightly"
      script: npm run truffle:test
      env: SOLC_NIGHTLY=true
